name: Sync Forks

on:
  schedule:
    - cron: '0 0 * * *'  # 每天凌晨执行
  workflow_dispatch:  # 添加手动触发器

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_TOKEN }}

    - name: Set up GitHub CLI
      run: |
        echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV

    - name: Sync fork 1
      run: |
        rm -rf repo1
        gh repo clone your-username/repo1 repo1
        cd repo1
        git remote add upstream https://github.com/original-owner/repo1.git
        git pull upstream main
        git push origin main

    - name: Sync fork 2
      run: |
        rm -rf repo2
        gh repo clone your-username/repo2 repo2
        cd repo2
        git remote add upstream https://github.com/original-owner/repo2.git
        git pull upstream develop
        git push origin develop
