name: Sync Forks

on:
  schedule:
    - cron: '0 0 * * *'  # 每天凌晨执行
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_TOKEN }}

    - name: Set up GitHub CLI
      run: |
        echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV

    - name: Get list of forked repositories
      run: |
        gh repo list --limit 1000 --json nameWithOwner,isFork --jq '.[] | select(.isFork == true) | .nameWithOwner' > repos.txt

    - name: Sync forked repositories
      run: |
        while read repo; do
          echo "Syncing $repo"
          gh repo sync "$repo" --force
        done < repos.txt
