name: Sync Forks

on:
  schedule:
    - cron: '0 0 * * *'  # 每天凌晨执行
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_TOKEN }}

    - name: Set up GitHub CLI
      run: |
        echo "GH_TOKEN=${{ secrets.GH_TOKEN }}" >> $GITHUB_ENV

    - name: Get list of forked repositories
      run: |
        gh repo list --limit 1000 --json nameWithOwner --jq '.[].nameWithOwner' > repos.txt

    - name: Sync forked repositories
      run: |
        while read repo; do
          echo "Syncing $repo"
          rm -rf "$repo"
          gh repo clone "$repo"
          cd "$(basename "$repo")"
          upstream_repo="$(echo "$repo" | sed "s/^${{ github.repository_owner }}\//${ORIGINAL_OWNER}\//")
          git remote add upstream "https://github.com/$upstream_repo.git"
          git pull upstream HEAD
          git push origin HEAD
          cd ..
        done < repos.txt
      env:
        ORIGINAL_OWNER: original-owner  # 替换为上游仓库的所有者
